### ISSUE TITLE
After reinstalling from local, deploy warns about links being overridden externally

### ISSUE THREAD

**Issue by ZetaDaemon** [limo-app/limo#25]
As title says, whenever i reinstall from local im now presented with a dialog box telling my files have been overwritten externally. this happens every time i reinstall from local, even if i havent touched any of my files
![image](https://github.com/user-attachments/assets/818f025e-9ac4-41d7-ba9b-5654d6b0dbd0)

**Comment by limo-app** [comment]
Can confirm. When reinstalling the files in the mod's directory are overwritten and therefore the hard links in the target directory no longer point to the same location. I am not yet sure what the best solution for this issue is, but will address it in the upcoming update.
In the meantime: If you frequently reinstall mods you could test if sym links work for you, they are not affected by this issue.
Just to be clear: If you want to keep the new files, do NOT accept any of the changes in that dialog.
