### ISSUE TITLE
Skyrim SE fails to launch with SKSE on Steam Flatpak

### ISSUE THREAD

**Issue by Alexandersonis** [limo-app/limo#35]
### Problem:
I followed the Limo Wiki tutorial to install Skyrim SE mods. So far, I’ve only installed SKSE, but Skyrim fails to start with it.

The standard command `steam -applaunch 489830` doesn't work. 
So, I tried the command `flatpak run com.valvesoftware.Steam --applaunch 489830` (specific for Flatpak), but Skyrim launches without SKSE.

### Question:
Did I understand correctly that the renamed copy of skse64_loader.exe should stay in the Bin folder after being renamed to SkyrimSELauncher.exe, or is there something else that needs to be configured?

### Logs:
Attempt with steam -applaunch 489830:
2024-09-26 20:30:26 [Info]: Running application 'Skyrim SE' with command 'steam -applaunch 489830'
2024-09-26 20:30:26 [Info]: Application 'Skyrim SE' exited with return code 256

Attempt with flatpak run com.valvesoftware.Steam --applaunch 489830:
2024-09-26 21:07:00 [Info]: Running application 'Skyrim SE' with command 'flatpak run com.valvesoftware.Steam --applaunch 489830'
2024-09-26 21:07:00 [Info]: Application 'Skyrim SE' exited with return code 0

### System Information:
Limo version: Flatpak 1.0.7
Steam version: Flatpak
OS: Linux Mint Debian Edition 6 (LMDE 6)

**Comment by limo-app** [comment]
> So, I tried the command `flatpak run com.valvesoftware.Steam --applaunch 489830` (specific for Flatpak), but Skyrim launches without SKSE.

Thank you for reporting this, i forgot to adapt the imported launch command for flatpak steam installations.

> Did I understand correctly that the renamed copy of skse64_loader.exe should stay in the Bin folder after being renamed to SkyrimSELauncher.exe, or is there something else that needs to be configured?

When you launch Skyrim through Steam, the Skyrim launcher (*SkyrimSELauncher.exe*) is run by default. When you rename the SKSE executable (*skse64_loader.exe*) in your mod's folder, the original launcher file gets overwritten when deploying. Afterwards both Steam and Limo should launch Skyrim through SKSE. To verify if this is done correctly, please check if *skse64_loader.exe* and *SkyrimSELauncher.exe* in your Skyrim's installation directory are identical. (Checking the file size should be enough)

**Comment by Alexandersonis** [comment]
Thanks for the clarification. I initially thought that Limo would automatically deploy mods when launching the game through Limo, but I realized you have to manually press "Deploy" beforehand.

After some testing, I found that on my System only the "Copy" deployment mode works fine. 
Sym Links get created but are not working, and there are no errors in the logs.
Hard links fail with the following error (even though both directories are on the same partition):
`
2024-09-30 21:25:28 [Error]: Could not create hard link from "/home/fabian/Mods/Skyrim/Staging" to "/home/fabian/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Skyrim Special Edition/Data". Ensure that both directories are on the same partition! Alternatively: Switch to sym link deployment.`

**Comment by limo-app** [comment]
> Hard links fail with the following error (even though both directories are on the same partition):

This is due to how the Flatpak sandbox works. Even if you grant an app access to your home directory, it cannot read or write files in `~/.var/app`, since this is where Flatpaks are installed. The only reason Limo can access files from a Flatpak Steam installation is because it has an additional permission to read/ write to `~/.var/app/com.valvesoftware.Steam`. Since Flatpak uses a bind mount for each additional directory an app can access and hard links do not work across bind mounts, Limo cannot create hard links between files in your home directory and files in the Steam installation.
A possible workaround is to create a new steam library folder in your home directory (e.g. in `~/steam`) and then install the game there. Unless you only want to install a handful of small mods, i heavily recommend doing this instead of using copy deployment.

> Sym Links get created but are not working

Could you clarify what this means? Does the game not work when using sym links or are the links themselves somehow broken?

**Comment by Alexandersonis** [comment]
I found the issue was that Steam, running via Flatpak, didn’t have the necessary permission to access the mods folder where the symlinks were pointing. After granting Steam the required filesystem permissions, the game and mods started working as expected. So, the symlinks themselves were fine, but it was a permission problem within the Flatpak sandbox that prevented them from functioning properly.
