### ISSUE TITLE
Deployer for OpenMW

### ISSUE THREAD

**Issue by poperigby** [limo-app/limo#40]
It would be very helpful to have a deployer for OpenMW, that adds data directories and plugins to [`openmw.cfg`](https://openmw.readthedocs.io/en/stable/reference/modding/mod-install.html). OpenMW has a launcher that allows you to manage mods, but it's very rudimentary. It doesn't allow you to just drag archives in like LIMO, so you have to set up all the directories yourself and then add them in the launcher.

**Comment by Heisenborgar** [comment]
+1 for this. This is a must have 😭

**Comment by limo-app** [comment]
Somehow missed this issue, sorry. Will add a deployer that automatically adds entries to `openmw.cfg`. 

Am i correct in assuming that LOOT does not work here?
 If so the deployer would only allow enabling/ disabling and manually reordering files. Auto sort would not work, since there would be no way of detecting conflicts.

**Comment by poperigby** [comment]
> Am i correct in assuming that LOOT does not work here?

No LOOT doesn't work with OpenMW as far as I can tell. Not like the masterlist is very well updated anyway.

>  If so the deployer would only allow enabling/ disabling and manually reordering files. Auto sort would not work, since there would be no way of detecting conflicts.

Do you mean for loose files or plugins?

**Comment by limo-app** [comment]
> Do you mean for loose files or plugins?

Plugins. I will test if LOOT shows conflicts for them even if auto sorting will be useless, seeing conflicts would help.

**Comment by limo-app** [comment]
53012d90d2bd624060532d45db91fbcdb49cbfd4 adds two new deployer types:
1. **OpenMW Plugin Deployer**: This is basically a LOOT Deployer except that it manages plugins in `openmw.cfg`.
2. **OpenMW Archive Deployer**: Manages archive (.bsa) files in `openmw.cfg`. Does not support auto-sort and cannot show conflicts between archives.

A few notes:
- Target directories for both deployers should point to the directory containing `openmw.cfg`
- If you are using the Flatpak versions of both Limo and OpenMW: Make sure you allow Limo to access `~/.var/app/org.openmw.OpenMW/`
- While the plugin deployer does support auto sorting through LOOT, the outdated masterlist may lead to an incorrect order. You can improve this by creating your own `userlist.yaml` with custom rules
- As with the LOOT deployer, you do not need to click *Deploy* in order for changes to be applied. Instead, deploying simply updates the list of plugins/ archives
- Due to the way the OpenMW launcher manages plugins, Limo will auto-enable all plugins the first time you set up the plugin deployer, even those disabled in the OpenMW launcher.
- Because of the above, it is best not to use the launcher for plugin management when using the new deployers


The changes should be live for Flatpak Limo in a few hours.

**Comment by poperigby** [comment]
Thank you!

**Comment by poperigby** [comment]
@limo-app It would also be useful for the plugin deployer to recognize .omwscripts, .omwgame, and .omwaddon :)
