### ISSUE TITLE
All plugins have "Vanilla" listed as their source mod

### ISSUE THREAD

**Issue by poperigby** [limo-app/limo#68]
![Screenshot_2024-11-21_22-57](https://github.com/user-attachments/assets/c6073521-4b49-496c-8c5b-2271666ba2ac)

Seems to be incorrectly grabbing it?

**Comment by poperigby** [comment]
Not sure what happened but it seems to have fixed itself.

**Comment by limo-app** [comment]
I wanted to clarify this earlier but something else came up so i had no time. 
The reason this happens is because plugin sources are only updated and then cached when you deploy. This is done because checking for mod sources may take some time for large mod lists.
The issue you describe will only occur once after updating to 1.0.9 and before deploying.
