### ISSUE TITLE
"“wine” (No such file or directory)": Issue with Wine as Runtime option

### ISSUE THREAD

**Issue by Saigaiii** [limo-app/limo#70]
Steamdeck
SteamOS 3.6.20

Not sure what the issue is, but when setting Wine as the Runtime for my tool, I get an error in the log that Im not sure how to fix. 

My log output is: 

"Running tool 'Bloodborne Enhanced GUI Patcher' with command 'flatpak-spawn --host --env=WINEPREFIX="/home/deck/.wine" wine "/home/deck/Games/ShadPS4/Games/CUSA03173/bb_enhanced_0.9.5/BBEnhancedPatcherGUI.exe"'
2024-11-22 09:31:22 [Info]: Tool 'Bloodborne Enhanced GUI Patcher' output: Portal call failed: Failed to start command: Failed to execute child process “wine” (No such file or directory) 
2024-11-22 09:31:22 [Info]: Tool 'Bloodborne Enhanced GUI Patcher' exited with return code 1"

Could this be because I do not have Wine flatpack? I use Q4Wine flatpack, but I should probably try it with Wine flatpack from the discover store.

Edit: Nevermind that did not fix it. I cannot even add the directory as it seems it does not recognize it as a wine directory. 

Wine directory: /home/deck/.var/app/org.winehq.Wine/data/wine

Q4wine directory: /home/deck/.wine

**Comment by Saigaiii** [comment]
Also I would like to ask how I can make the tool open a konsole to execute a linux executable file? Not sure really how or where to do that on the tools page.

**Comment by limo-app** [comment]
It looks like the command fails because wine could be found on your device. This is likely because the wine executable is not in a `bin` directory (e.g. `/usr/bin`) that is checked when looking for a command. If this is the case, then opening a terminal any typing
```
wine --version
```
should not work either.
If you know where your wine executable is, you can set that directory as working directory. Let's say `wine` is at `/home/deck/.wine/wine`, then you set the working directory to `/home/deck/.wine`.
I do not own a Steam deck so i cannot varify this, but if you install wine (the non flatpak version) through Discover, the executable should automatically be installed in a way that allows Limo to find it.

> Could this be because I do not have Wine flatpack? I use Q4Wine flatpack, but I should probably try it with Wine flatpack from the discover store.
> 
> Edit: Nevermind that did not fix it. I cannot even add the directory as it seems it does not recognize it as a wine directory.
> 
> Wine directory: /home/deck/.var/app/org.winehq.Wine/data/wine

Flatpak uses a sandbox for every application. This prevents them from seeing applications in `~/.var/app`, which is why you cannot add that directory. To fix this, you could use a tool like [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) to give Limo access to `/home/deck/.var/app/org.winehq.Wine/`.

> Also I would like to ask how I can make the tool open a konsole to execute a linux executable file? Not sure really how or where to do that on the tools page.

Limo essentially does this in the background when you run a tool. If you have a specific executable you wish to run, create a tool with the *Native* runtime and paste the entire path to the tool into the *Tool executable* field.

**Comment by Saigaiii** [comment]
> should not work either. If you know where your wine executable is, you can set that directory as working directory. Let's say `wine` is at `/home/deck/.wine/wine`, then you set the working directory to `/home/deck/.wine`. I do not own a Steam deck so i cannot varify this, but if you install wine (the non flatpak version) through Discover, the executable should automatically be installed in a way that allows Limo to find it.

I tried to set the working directory to /home/deck/.wine and it still returns with an error. Here is the log: 

"2024-11-23 21:01:32 [Info]: Running tool 'Bloodborne Enhanced GUI Patcher' with command 'flatpak-spawn --host --directory="/home/deck/.wine" --env=WINEPREFIX="/home/deck/.wine" wine "/home/deck/Games/ShadPS4/Games/CUSA03173/bb_enhanced_0.9.5/BBEnhancedPatcherGUI.exe"'
2024-11-23 21:01:32 [Info]: Tool 'Bloodborne Enhanced GUI Patcher' output: Portal call failed: Failed to start command: Failed to execute child process “wine” (No such file or directory) 
2024-11-23 21:01:32 [Info]: Tool 'Bloodborne Enhanced GUI Patcher' exited with return code 1"

> Flatpak uses a sandbox for every application. This prevents them from seeing applications in `~/.var/app`, which is why you cannot add that directory. To fix this, you could use a tool like [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) to give Limo access to `/home/deck/.var/app/org.winehq.Wine/`.

So I tried with Flatseal to allow Limo to see the directory of "/home/deck/.var/app/org.winehq.Wine/data/wine/", and I still get the same error. Im not sure if I am installing the wrong version of Wine in the discover store or something. 

> Limo essentially does this in the background when you run a tool. If you have a specific executable you wish to run, create a tool with the _Native_ runtime and paste the entire path to the tool into the _Tool executable_ field.

Also I did this but no Konsole comes up. In the log it just displays this: 

Running tool 'Bloodborne Chalice Dungeon Save Injector' with command 'flatpak-spawn --host "/home/deck/Games/ShadPS4/user/savedata/1/CUSA03173/SPRJ0005/OidaChalice"'

**Comment by limo-app** [comment]
> Also I did this but no Konsole comes up. In the log it just displays this:

Try creating a tool in *Manual* mode and use this as command:
```
konsole --hold --separate -e <command>
```
So in this case:
```
konsole --hold --separate -e /home/deck/Games/ShadPS4/user/savedata/1/CUSA03173/SPRJ0005/OidaNiceChalice_v2_linux-x64
```

> I set the tool executable to the exe and the wine prefix and working directory to:
> /home/deck/.wine and it also produces the same error.

Can you manually launch wine from Konsole? Like this:
```
wine /home/deck/Games/ShadPS4/Games/CUSA03173/bb_enhanced_0.9.5/BBEnhancedPatcherGUI.exe
```
