### ISSUE TITLE
filesystem error: cannot rename: Invalid cross-device link

### ISSUE THREAD

**Issue by poperigby** [limo-app/limo#79]
I'm getting the following error when trying to install the main file from [this](https://www.nexusmods.com/skyrimspecialedition/mods/66339?tab=files) mod:

```
2024-12-07 10:30:36 [Error]: filesystem error: cannot rename: Invalid cross-device link [/home/cassidy/Games/Modding/Games/Skyrim/lmm_tmp_extract0/Messages/Better Courier - Green/Scripts] [/Scripts]
```

**Comment by limo-app** [comment]
This was caused by the mod author using the absolute path `/Scripts` as a destination for the FOMOD installation. Since allowing this is never useful, [d995e58](https://github.com/limo-app/limo/commit/d995e58a71511fc247652b8ddfe255cefd4d51c1) fixes this by making all FOMOD destination paths relative.

**Comment by poperigby** [comment]
I'm glad I'm able to find all these horrible FOMODs to test Limo haha.
